[package]
name = "abc-product"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
csv = "1.4.0"
ean13 = { git = "https://github.com/areif-dev/ean13", version = "0.4.1" }
rust_decimal = "1.39.0"
